"""add global_settings

Revision ID: f8375746a268
Revises: a7b8c9d0e1f2
Create Date: 2026-07-27 11:24:44.376180

Generic per-entity settings: one ``config`` JSON row per (entity_type, entity_id),
validated against the entity type's registered Pydantic schema. First consumer is
the gold data-availability schedule. Unique index ``uq_global_settings_entity``
enforces one row per (entity_type, entity_id).

"""

from typing import Sequence, Union

import kactus_common.database.oltp.types
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f8375746a268"
down_revision: Union[str, Sequence[str], None] = "a7b8c9d0e1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_settings",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "id", mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "create_time",
            kactus_common.database.oltp.types.DateTimeTzAware(),
            nullable=True,
        ),
        sa.Column(
            "update_time",
            kactus_common.database.oltp.types.DateTimeTzAware(),
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            mysql.BIGINT(unsigned=True),
            nullable=True,
            comment="update user id",
        ),
        sa.Column(
            "created_by",
            mysql.BIGINT(unsigned=True),
            nullable=True,
            comment="create user id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_global_settings_entity_id"),
        "global_settings",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_global_settings_entity_type"),
        "global_settings",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        "uq_global_settings_entity",
        "global_settings",
        ["entity_type", "entity_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_global_settings_entity", table_name="global_settings")
    op.drop_index(op.f("ix_global_settings_entity_type"), table_name="global_settings")
    op.drop_index(op.f("ix_global_settings_entity_id"), table_name="global_settings")
    op.drop_table("global_settings")
    # ### end Alembic commands ###
